### ISSUE TITLE
Viewing the data

### ISSUE THREAD

**Issue by mcincera** [mattshax/cesium_pnt_generator#6]
Hello Matthew, 
thank you for your code. I'm trying to visualize my terrestrial laser-scanner data in Cesium. I used your code to create the tileset. Everything looks good, the JSON and PNTS files get created. I have some issues using your viewer though. It gets loaded, but I can't see my data. I tried to view the sample data of the stadium, but that doesn't work well either. The point cloud is visible only from certain angles, the base layer won't load etc. So I'm not sure if it's an issue of the viewer, or my data..

I tried to load the tiles in Cesium Sandcastle using the template https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Point%20Cloud.html, but I'm getting an error message: 
"A 3D tile failed to load: /scan-0001.pnts?v=0.0
Error: Unexpected token � in JSON at position 0"
I ran the  JSON file through a validator and it seems to be ok.

I'm running the code on Windows 10 with subsystem for Linux, if that's relevant. 

Could you help me figure out, what I'm doing wrong?
Thanks

**Comment by mcincera** [comment]
Hello again, nevermind, I've solved the problem with the viewer already. There were some minor issues with the html file, but mainly it was caused by the _geometricError_ parameter, which was set to "0" in the generated tileset.json file and caused the tiles never to render.

**Comment by ThornM9** [comment]
This critical error isn't actually fixed, not sure why this issue was closed. It makes this tool basically unusable.
